package de.holisticon.emapp.ui;



import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.Sizeable;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.VerticalLayout;

import de.holisticon.emapp.ApplicationEventBus;
import de.holisticon.emapp.event.LogoutEvent;
import de.holisticon.emapp.handler.SwitchToTimeTrackingRecordEditorEventHandler;

@SuppressWarnings("serial")
public class MainComponent extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private MenuBar footerMenuBar;
	@AutoGenerated
	private HorizontalSplitPanel masterDetails;
	@AutoGenerated
	private WelcomeDashboard welcomeDashboard_1;
	@AutoGenerated
	private VerticalLayout masterLayout;
	@AutoGenerated
	private TopicSwitch topicSwitch_1;
	@AutoGenerated
	private MenuBar headerMenuBar;
	@AutoGenerated
	private HorizontalLayout titleArea;
	@AutoGenerated
	private Embedded logo;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public MainComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		setDebugId("_mainComponent");

		ApplicationEventBus.register(new SwitchToTimeTrackingRecordEditorEventHandler(masterDetails));

		masterDetails.setSplitPosition(200, Sizeable.UNITS_PIXELS);

		footerMenuBar.addItem("Quit", new ThemeResource("../img/quit_16x16.png"), new Command() {
			public void menuSelected(MenuItem selectedItem) {
				ApplicationEventBus.post(new LogoutEvent());
			}
		});
		

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// titleArea
		titleArea = buildTitleArea();
		mainLayout.addComponent(titleArea);

		// headerMenuBar
		headerMenuBar = new MenuBar();
		headerMenuBar.setImmediate(false);
		headerMenuBar.setWidth("100.0%");
		headerMenuBar.setHeight("-1px");
		mainLayout.addComponent(headerMenuBar);

		// masterDetails
		masterDetails = buildMasterDetails();
		mainLayout.addComponent(masterDetails);
		mainLayout.setExpandRatio(masterDetails, 1.0f);

		// footerMenuBar
		footerMenuBar = new MenuBar();
		footerMenuBar.setImmediate(false);
		footerMenuBar.setWidth("100.0%");
		footerMenuBar.setHeight("-1px");
		mainLayout.addComponent(footerMenuBar);

		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildTitleArea() {
		// common part: create layout
		titleArea = new HorizontalLayout();
		titleArea.setImmediate(false);
		titleArea.setWidth("100.0%");
		titleArea.setHeight("-1px");
		titleArea.setMargin(true);
		titleArea.setSpacing(true);

		// logo
		logo = new Embedded();
		logo.setImmediate(false);
		logo.setWidth("-1px");
		logo.setHeight("-1px");
		logo.setSource(new ThemeResource("../img/holisticon-logo.png"));
		logo.setType(1);
		logo.setMimeType("image/png");
		titleArea.addComponent(logo);
		titleArea.setExpandRatio(logo, 1.0f);

		return titleArea;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildMasterDetails() {
		// common part: create layout
		masterDetails = new HorizontalSplitPanel();
		masterDetails.setImmediate(false);
		masterDetails.setWidth("100.0%");
		masterDetails.setHeight("100.0%");
		masterDetails.setMargin(false);

		// masterLayout
		masterLayout = buildMasterLayout();
		masterDetails.addComponent(masterLayout);

		// welcomeDashboard_1
		welcomeDashboard_1 = new WelcomeDashboard();
		welcomeDashboard_1.setImmediate(false);
		welcomeDashboard_1.setWidth("100.0%");
		welcomeDashboard_1.setHeight("100.0%");
		masterDetails.addComponent(welcomeDashboard_1);

		return masterDetails;
	}

	@AutoGenerated
	private VerticalLayout buildMasterLayout() {
		// common part: create layout
		masterLayout = new VerticalLayout();
		masterLayout.setImmediate(false);
		masterLayout.setWidth("100.0%");
		masterLayout.setHeight("100.0%");
		masterLayout.setMargin(false);

		// topicSwitch_1
		topicSwitch_1 = new TopicSwitch();
		topicSwitch_1.setImmediate(false);
		topicSwitch_1.setWidth("100.0%");
		topicSwitch_1.setHeight("100.0%");
		masterLayout.addComponent(topicSwitch_1);
		masterLayout.setExpandRatio(topicSwitch_1, 1.0f);

		return masterLayout;
	}

}
